apiVersion: v1
kind: Service
metadata:
  name: countdown-backend
  namespace: countdown
  labels:
    app: countdown-backend
spec:
  selector:
    app: countdown-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
