apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-credentials
  namespace: monitoring
type: Opaque
stringData:
  access-key-id: <YOUR_AWS_ACCESS_KEY_ID>
  secret-access-key: <YOUR_AWS_SECRET_ACCESS_KEY>
  session-token: <YOUR_AWS_SESSION_TOKEN>
